Functioning AddFood, Confirm pages, changed test language to python. Small fix to my-reports page
hekolcu/vitamis pull request #31
Opened 2024-05-01 14:48 UTC by AdnanAlperAvci

Fixed getting null exception when user doesnt have any records/reports

2024-05-01 15:04 UTC, hekolcu requested changes
VitamisFrontendTest/bin ve obj gibi directory leri gitignore a ekler misin

2024-05-03 11:02 UTC, hekolcu commented
VitamisFrontendTest/bin ve obj gitignore a ekledin teşekkürler. fakat commitin içinde duruyorlar hala
![image](https://github.com/hekolcu/vitamis/assets/98216365/2f2c0082-f1e6-417c-b379-fe1eef4dd556)
Lütfen onlar committen çıkartır mısın. Çok zorlaştırıyor merge ı

2024-05-03 12:06 UTC, AdnanAlperAvci commented
> VitamisFrontendTest/bin ve obj gitignore a ekledin teşekkürler. fakat commitin içinde duruyorlar hala ![image](https://private-user-images.githubusercontent.com/98216365/327734845-2f2c0082-f1e6-417c-b379-fe1eef4dd556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzgxNTMsIm5iZiI6MTcxNDczNzg1MywicGF0aCI6Ii85ODIxNjM2NS8zMjc3MzQ4NDUtMmYyYzAwODItZjFlNi00MTdjLWIzNzktZmUxZWVmNGRkNTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDEyMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNzk0MDcwNmJjY2FlOWZjZmM2MjVkNGFjYTQ0ZTA0ZDJkZGNiN2I0OWVjOTUwYTllYzM0YmM1ZWRiOTcyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wEVtvZbStfG2UwkNlQWTnBendMjCw7i7XdVJKWV8dv4) Lütfen onlar committen çıkartır mısın. Çok zorlaştırıyor merge ı

Tam ne yapmam lazım? Birşeyler denedim ama hala gözüküyor

2024-05-03 16:12 UTC, AdnanAlperAvci commented
> > VitamisFrontendTest/bin ve obj gitignore a ekledin teşekkürler. fakat commitin içinde duruyorlar hala ![image](https://private-user-images.githubusercontent.com/98216365/327734845-2f2c0082-f1e6-417c-b379-fe1eef4dd556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzgxNTMsIm5iZiI6MTcxNDczNzg1MywicGF0aCI6Ii85ODIxNjM2NS8zMjc3MzQ4NDUtMmYyYzAwODItZjFlNi00MTdjLWIzNzktZmUxZWVmNGRkNTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDEyMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNzk0MDcwNmJjY2FlOWZjZmM2MjVkNGFjYTQ0ZTA0ZDJkZGNiN2I0OWVjOTUwYTllYzM0YmM1ZWRiOTcyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wEVtvZbStfG2UwkNlQWTnBendMjCw7i7XdVJKWV8dv4) Lütfen onlar committen çıkartır mısın. Çok zorlaştırıyor merge ı
> 
> Tam ne yapmam lazım? Birşeyler denedim ama hala gözüküyor

Şimdilik böyle kalsın en son yaparız testleri

2024-05-03 19:21 UTC, merged